# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NODE_VERSION: 22.x
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Instalando nodeJS ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm
    
    #- name: Cache
    #  id: cache
    #  uses: actions/cache@v3
    #  with:
    #    path: node_modules
    #    key: deps-npm-'${{ hashFiles('**/package-lock.json') }}'
    - name: Instalação de Dependencias
      #if: steps.cache.outputs.cache-hit != 'failure'
      run: npm ci

    - name: Realizando o Build
      run: npm run build --if-present
    
    #- name: Executando lint
    #  run: npm run lint
    
    - name: Realizando testes
      run: npm test
    
    - name: Publicando DIST
      uses: actions/upload-artifact@v4
      with:
         name: node-dist
         path: dist/
  report:
    runs-on: ubuntu-latest
    needs: [build]
    container: 
      image: alpine:latest
    steps:
      - name: Report
        run: cat /etc/*ease && echo "${{ toJson(github) }}"




        
